language: php
php:
  - 5.5
  - 5.4
  - 5.3


# Specify versions of WordPress to test against
# WP_VERSION = WordPress version number (use "master" for SVN trunk)
# WP_MULTISITE = whether to test multisite (use either "0" or "1")
env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1

# Grab the setup script and execute
before_script:
    - wget https://raw.github.com/benbalter/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh

